# Generated by Django 2.2.6 on 2019-12-04 11:35

from django.db import migrations, models
import django.db.models.deletion
import software.models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20191112_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contents',
            field=models.TextField(help_text="The main contents of the software page. Markdown is supported. Image names should follow the path '/media/images/about/'. Example: '/media/images/software/figure_name.png'."),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(storage=software.models.OverwriteStorage(), upload_to='images/software')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='software.Content')),
            ],
        ),
    ]
