# Generated by Django 2.2 on 2020-02-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_auto_20191204_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contents',
            field=models.TextField(help_text="The main contents of the software page. Markdown is supported. Image names should follow the path '/media/images/software/'. Example: '/media/images/software/figure_name.png'."),
        ),
    ]
