# Generated by Django 2.2.6 on 2019-10-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibentry',
            name='authors',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bibentry',
            name='doi_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bibentry',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
