# Generated by Django 2.2.6 on 2019-10-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20191025_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibentry',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
