# Generated by Django 2.2.6 on 2019-10-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_bibentry_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibentry',
            old_name='issue',
            new_name='volume_and_issue',
        ),
    ]
