# Generated by Django 2.2.6 on 2019-11-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20191112_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.CharField(default='Journal article', help_text='Type of publication, example: Journal article, conference paper', max_length=100),
        ),
    ]
