# Generated by Django 2.2 on 2020-02-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_publication_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='open_access_url',
            field=models.CharField(blank=True, help_text='Optional, link to open access source.', max_length=100),
        ),
    ]
