# Generated by Django 2.2 on 2020-02-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20200206_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(default=2000, help_text='Publication year. Used for sorting. NOT DISPLAYED!'),
        ),
    ]
