# Generated by Django 2.2 on 2020-02-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20200206_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField(help_text='List of authors', max_length=200)),
                ('title', models.TextField(help_text='Title of the publication', max_length=200)),
                ('year', models.IntegerField(default=2000, help_text='Publication year. Used for sorting. NOT DISPLAYED!')),
                ('type', models.CharField(default='Journal article', help_text='Type of publication, example: Journal article, conference paper', max_length=100)),
                ('info', models.TextField(help_text='Example: journal name, issue, pages, publication year')),
                ('doi_url', models.CharField(help_text="Link to publisher's webpage.", max_length=100)),
                ('open_access_url', models.CharField(blank=True, help_text='Optional, link to open access source.', max_length=100)),
            ],
        ),
    ]
