# Generated by Django 3.2.9 on 2021-11-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialfile',
            name='name',
            field=models.CharField(default='name', help_text='Name associated with the file.', max_length=100),
            preserve_default=False,
        ),
    ]
