# Generated by Django 3.2.9 on 2021-11-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_materialfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialfile',
            name='description',
            field=models.TextField(default='File description', help_text='Short description about the file.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialentry',
            name='description',
            field=models.TextField(help_text='Short description about the materials under this category.', max_length=1000),
        ),
    ]
