# Generated by Django 2.2 on 2020-02-06 13:57

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191112_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='contents',
            field=models.TextField(help_text="The contents of the blog post. Markdown is supported. Image names should follow the path 'media/images/blog/'. Example: '/media/images/blog/figure_name.png"),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='pub_date',
            field=models.DateField(help_text='Publication date'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(storage=blog.models.OverwriteStorage(), upload_to='images/blog')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.BlogContent')),
            ],
        ),
    ]
