# Generated by Django 2.2.6 on 2019-10-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
