# Generated by Django 2.2.6 on 2019-10-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0002_auto_20191024_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
