# Generated by Django 2.2.6 on 2019-11-12 08:33

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0003_auto_20191024_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=stdimage.models.StdImageField(upload_to='images/'),
        ),
    ]
