# Generated by Django 2.2.6 on 2019-11-12 11:24

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0004_auto_20191112_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Max length 100 characters.', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bio',
            name='description',
            field=models.TextField(help_text='Max length 1000 characters.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=stdimage.models.StdImageField(help_text='Image ratio should be 1:1 and size greater than 140 by 140 pixels.', upload_to='images/'),
        ),
    ]
