# Generated by Django 2.2.6 on 2019-11-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0005_auto_20191112_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='keywords',
            field=models.CharField(default='none', help_text='Keywords to give a brief idea of fields of expertise', max_length=100),
            preserve_default=False,
        ),
    ]
