# Generated by Django 2.2.6 on 2019-12-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0008_auto_20191216_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercontributor',
            name='surname',
            field=models.CharField(default='Surname', help_text='Used to order the names shown.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='othercontributor',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
