# Generated by Django 2.2.6 on 2019-12-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0009_auto_20191216_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='order',
            field=models.IntegerField(default=1, help_text='Used to override the surname ordering. Orders the profiles shown in ascending order, smaller is first.'),
        ),
    ]
