# Generated by Django 2.2.6 on 2019-10-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttext',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
