# Generated by Django 2.2.6 on 2019-12-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20191204_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contents',
            field=models.TextField(help_text="The main contents of the about page. Markdown is supported. Image names should follow the path '/media/images/about/'. Example: '/media/images/about/figure_name.png'."),
        ),
    ]
