# Generated by Django 2.2.6 on 2020-04-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_downloadable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This will also be the title used for the video.', max_length=100)),
                ('description', models.TextField(help_text='Short description about the video.', max_length=1000)),
                ('url', models.URLField(help_text='URL to a video supporting embedding.')),
            ],
        ),
    ]
