# Generated by Django 3.2.9 on 2021-11-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211103_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='An image to be displayed at the end of the news article.', upload_to='images/news'),
        ),
    ]
