# Generated by Django 3.2.9 on 2021-11-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_article_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=models.TextField(help_text="The textual content of the news article.  Markdown is supported. Image names should follow the path '/media/images/news/'. Example: '/media/images/news/figure_name.png'."),
        ),
    ]
