# Generated by Django 2.2.6 on 2019-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdescription',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publicationsdescription',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdescription',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
