# Generated by Django 2.2.6 on 2019-11-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20191111_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdescription',
            name='link',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationsdescription',
            name='link',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamdescription',
            name='link',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
