# Generated by Django 2.2.6 on 2019-11-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_carouselimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimages',
            name='description',
            field=models.TextField(default='None', max_length=1000),
            preserve_default=False,
        ),
    ]
