# Generated by Django 2.2.6 on 2019-11-12 07:22

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_carouselimages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimages',
            name='image',
            field=stdimage.models.StdImageField(upload_to='images/'),
        ),
    ]
