# Generated by Django 2.2.6 on 2019-11-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0007_auto_20191112_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurette',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featurette',
            name='image',
            field=models.ImageField(help_text='Image should be big, preferably bigger than 400 by 600 pixels.', upload_to='images/'),
        ),
    ]
