# Generated by Django 2.2.6 on 2019-12-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0008_auto_20191112_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurette',
            name='image',
            field=models.ImageField(help_text='Image should be big, preferably bigger than 800 by 400 pixels, and should have an aspect ratio of 2:1. If any padding is added, it should be transparent. Use a png format.', upload_to='images/'),
        ),
    ]
