# Generated by Django 2.2.6 on 2019-12-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0009_auto_20191204_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurette',
            name='text_content',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
