# Generated by Django 2.2.6 on 2019-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0010_auto_20191204_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimages',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='text_content',
            field=models.TextField(max_length=1000),
        ),
    ]
