# Generated by Django 3.2.9 on 2021-11-03 12:52

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0013_auto_20200206_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimages',
            name='image',
            field=stdimage.models.StdImageField(help_text='Image should be 1200x600 pixels, or bigger. Use a png format if the image has transparent sections.', upload_to='images/'),
        ),
    ]
